services:
  service-a:
    build: ./python/service-a
    ports:
      - "3100:3000"
    depends_on:
      - service-b
    environment:
      - TAX_SERVICE_URL=http://service-b:4000
      - FRONTEND_URL=http://13.48.3.238:5173

  
  service-b:
    build: ./python/service-b
    ports:
      - "3200:4000"
  
  frontend:
    build: ./tax-calculator-frontend
    ports:
      - "5173:80"
    depends_on:
      - service-a
      

  